function [fields] = stimField(Stimtype)
    switch Stimtype
        case 'Spontaneous'
            fields ={};
        case 'driftingGrating'
            fields = {'numTrials',...
                'doBlank',...
                'changeDirectionAt',...
                'stimDuration',...
                'isi',...
                'isRandom',...
                'initialDelay',...
                'temporalFreq',...
                'spatialFreq',...
                'contrast',...
                'textureType',...
                'maxv',...
                'minv',...
                'dutyCycle',...
                'foregroundColor',...
                'startingPhase',...
                'centerPoint',...
                'stimSize',...
                'animalOrientation'
                };
        case 'driftingGrating_Intrinsic'
            fields = {'numTrials',...
                'doBlank',...
                'changeDirectionAt',...
                'stimDuration',...
                'isi',...
                'isRandom',...
                'initialDelay',...
                'temporalFreq',...
                'spatialFreq',...
                'contrast',...
                'textureType',...
                'maxv',...
                'minv',...
                'dutyCycle',...
                'foregroundColor',...
                'startingPhase',...
                'centerPoint',...
                'stimSize',...
                'animalOrientation'
                };
        case 'driftingGrating_ori_sf'
            fields = {'numTrials',...
                    'doBlank',...
                    'changeDirectionAt',...
                    'stimDuration',...
                    'isi',...
                    'isRandom',...
                    'initialDelay',...
                    'temporalFreq',...
                    'spatialFreq',...
                    'contrast',...
                    'textureType',...
                    'numOrientations',...
                    'dutyCycle',...
                    'foregroundColor',...
                    'startingPhase',...
                    'centerPoint',...
                    'stimSize',...
                    'orientations',...
                    };
        case 'driftingGrating_ori_tf'
            fields = {'numTrials',...
                    'doBlank',...
                    'changeDirectionAt',...
                    'stimDuration',...
                    'isi',...
                    'isRandom',...
                    'initialDelay',...
                    'temporalFreq',...
                    'spatialFreq',...
                    'contrast',...
                    'textureType',...
                    'numOrientations',...
                    'dutyCycle',...
                    'foregroundColor',...
                    'startingPhase',...
                    'centerPoint',...
                    'stimSize',...
                    };
        case 'driftingGrating_CIB_shutter_3blanks'
            fields =  {'numTrials',...
                    'doBlank',...
                    'changeDirectionAt',...
                    'stimDuration',...
                    'isi',...
                    'isRandom',...
                    'isRandomOD',...
                    'initialDelay',...
                    'temporalFreq',...
                    'spatialFreq',...
                    'contrast',...
                    'textureType',...
                    'numOrientations',...
                    'stimPos',...
                    'stimSize',...
                    };
        case 'fullScreenFlash'
            fields = {'initialDelay',...
                'lum0',...
                'lum1',...
                'flashInterval',...
                'isi',...
                'numTrials'...
                'stimDuration',...
                };
        case 'Patch'
            fields = {'numTrials',...
                'doBlank',...
                'blankpercent',...
                'stimDuration',...
                'isi',...
                'isRandom',...
                'initialDelay',...
                'centerPoint',...
                'stimSize',...
                'numStimElev',...
                'numStimAzi',...
                };
        case 'Retinotopy_2D'
            fields = {'numberOfTrials',...
                'doBlank',...
                'stimDuration',...
                'ISI',...
                'isRandom',...
                'initialDelay',...
                'centerPoint',...
                'startPointx',...
                'endPointx',...
                'startPointy',...
                'endPointy',...
                'stimSize',...
                };
        case 'PatchGrating'
            fields = {'numTrials',...
                'doBlank',...
                'blankpercent',...
                'stimDuration',...
                'isi',...
                'isRandom',...
                'initialDelay',...
                'centerPos',...
                'stimPos',...
                'centerPoint',...
                'stimSize',...
                'numStimElev',...
                'numStimAzi',...
                'numOrientations',...
                };
        case 'rotatingGratingPatch'
            fields = {'numTrials',...
                'spinPeriodInSeconds',...
                'isi',...
                'initialDelay',...
                'centerPoint',...
                'stimPos',...
                'centerPoint',...
                'stimSize',...
                'numStimElev',...
                'numStimAzi',...
                };
        case 'SparseNoise'
            fields = {'stimDuration',...
                'isi',...
                'centerPoint',...
                'all', ...
                'trial',...
                };
        case 'azimuthBars'
            fields = {'numTrials',...
                'doBlank',...
                'blankpercent',...
                'stimDuration',...
                'isi',...
                'bwtime',...
                'isRandom',...
                'initialDelay',...
                'centerPos',...
                'stimPos',...
                'centerPoint',...
                'stimSize',...
                'numStimAzi',...
                'numOrientations',...
                'spatialFreq',...
                'minAzim',...
                };
        case 'azimuthBars_Checkd'
            fields = {'numTrials',...
                'doBlank',...
                'blankpercent',...
                'stimDuration',...
                'isi',...
                'bwtime',...
                'isRandom',...
                'initialDelay',...
                'centerPos',...
                'stimPos',...
                'centerPoint',...
                'stimSize',...
                'numStimAzi',...
                'numOrientations',...
                'spatialFreq',...
                'minAzim',...
                };
        case 'RF_local'
            fields = {'numTrials',...
                'doBlank',...
                'blankpercent',...
                'stimDuration',...
                'isi',...
                'bwtime',...
                'isRandom',...
                'initialDelay',...
                'centerPos',...
                'stimPos',...
                'centerPoint',...
                'stimSize',...
                'numStimAzi',...
                'numOrientations',...
                'spatialFreq',...
                'minAzim',...
                };
        case 'RF_localbar'
            fields = {'numTrials',...
                'doBlank',...
                'blankpercent',...
                'stimDuration',...
                'isi',...
                'isRandom',...
                'initialDelay',...
                'centerPos',...
                'stimPos',...
                'centerPoint',...
                'stimSize',...
                'numStimElev',...
                'numStimAzi',...
                'numOrientations',...
                'minAzim',...
                'minElev',...
                };
        case 'RetWedge'
            fields = {'numTrials',...
                'doBlank',...
                'nBlank',...
                'blankpercent',...
                'stimDuration',...
                'isi',...
                'isRandom',...
                'initialDelay',...
                'centerPos',...
                'stimSize',...
                'numWedges',...
                'temporalFreq',...
                'spatialFreq',...
                'numOrientations',...
                };
        case 'Ret_Annulus'
            fields = {'numTrials',...
                'doBlank',...
                'nBlank',...
                'blankpercent',...
                'stimDuration',...
                'isi',...
                'isRandom',...
                'initialDelay',...
                'centerPoint',...
                'startSize',...
                'numSizes',...
                'temporalFreq',...
                'spatialFreq',...
                'numOrientations',...
                };
        case 'MovingDots'
            fields = {'numTrials',...
                'doBlank',...
                'stimDuration',...
                'isi',...
                'isRandom',...
                'initialDelay',...
                'nDots',...
                'dotSize',...
                'contrast',...
                'fieldShape',...
                'dotLife',...
                'minv',...
                'fieldSize',...
                'speed',...
                'coherence',...
                'theta',...
                };
        case 'continuousEdge_withOrientationsAndTriggers'
            fields = {'numOrientations', ...
                'animalOrientation',...
                'barColor',...
                'backGroundColor',...
                'backGroundBarColor',...
                'isRandom',...
                'edgeWidth',...
                'centerPoint',...
                'numberOfTrials',...
                'initialDelay',...
                'movementPeriod',...
                'animalName'
                };
        case 'waveletStim_forJoe'
            fields = {'Iname',...
                'repeats',...
                'interRepeatInt',...
                'interMovieInt',...
                'stimFramesPerTrial',...
                'movies'

                };
        otherwise
            fields ={};
    end
end